services:
  - type: web
    name: aldar-real-estate
    env: node
    buildCommand: chmod +x build-render.sh && ./build-render.sh
    startCommand: NODE_ENV=production npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: aldar-postgres
          property: connectionString

databases:
  - name: aldar-postgres
    databaseName: aldar_db
    user: aldar_user